/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import entities.User;
import javax.swing.JOptionPane;
import services.UserService;
import ui.Main;


/**
 *
 * @author USER
 */
public class LoginForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLogin = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        bnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });

        bnLogin.setText("Login");
        bnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnLoginActionPerformed(evt);
            }
        });

        jLabel1.setText("Forgot password? ");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setText("Login :");

        jLabel3.setText("Password :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPassword)
                            .addComponent(txtLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(bnLogin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jLabel1)))
                .addContainerGap(275, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(bnLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(196, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnLoginActionPerformed
        // TODO add your handling code here:
        String login = txtLogin.getText().trim();
    String password = txtPassword.getText().trim();

    System.out.println("Login attempt: " + login);
    
    UserService us = new UserService();
    System.out.println("UserService created: " + (us != null));

    // ADD NULL CHECK HERE
    if (us == null) {
        System.out.println("UserService is NULL!");
        JOptionPane.showMessageDialog(this, "Service initialization failed!");
        return;
    }
    
    boolean connectionValid = us.isConnectionValid();
    System.out.println("Connection valid: " + connectionValid);
    
    if (!connectionValid) {
        JOptionPane.showMessageDialog(this, "Database connection failed! Please check if MySQL is running.");
        return;
    }

    System.out.println("Calling authenticate...");
    boolean authResult = us.authenticate(login, password);
    System.out.println("Authenticate result: " + authResult);
    
    if (authResult) {
        System.out.println("Authentication successful!");
        // OPEN MAIN WINDOW - WITH PROPER CONFIGURATION
        Main main = new Main();
        main.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        main.setLocationRelativeTo(null);
        main.setVisible(true);

        // CLOSE LOGIN WINDOW - SAFER APPROACH
        try {
            java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);
            if (window != null) {
                window.dispose();
            }
        } catch (Exception e) {
            System.out.println("Error closing window: " + e.getMessage());
            // Just hide the login form if we can't dispose the window
            this.setVisible(false);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Incorrect login or password!");
    }

    }//GEN-LAST:event_bnLoginActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked

    String login = txtLogin.getText().trim();
    UserService us = new UserService();
    User user = us.findByLogin(login);

    if (user == null) {
        JOptionPane.showMessageDialog(this, "Utilisateur introuvable !");
        return;
    }

    String email = JOptionPane.showInputDialog(this, "Entrez votre email :");
    if (email == null || email.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Email invalide !");
        return;
    }

    // Afficher la question secrète
    String answer = JOptionPane.showInputDialog(this, user.getQuestion());

    if (!us.verifySecurityAnswer(login, answer)) {
        JOptionPane.showMessageDialog(this, "Réponse incorrecte !");
        return;
    }

    String newPw = JOptionPane.showInputDialog(this, "Entrez un nouveau mot de passe :");
    if (newPw == null || newPw.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Mot de passe invalide !");
        return;
    }

    boolean done = us.resetPasswordAndSendEmail(login, email, newPw);

    if (done) {
        JOptionPane.showMessageDialog(this, "Mot de passe changé et email envoyé !");
    } else {
        JOptionPane.showMessageDialog(this, "Erreur lors de l’envoi de l'email.");
    }

        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables
}
