/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

/**
 *
 * @author HP
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main1
     */
    public Main() {
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuChambre = new javax.swing.JMenuItem();
        menuClient = new javax.swing.JMenuItem();
        menuReservation = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuClientReservations = new javax.swing.JMenuItem();
        Statistiques = new javax.swing.JMenu();
        menuOccupation = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenu1.setText("Gestion");

        menuChambre.setText("Chambre");
        menuChambre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuChambreActionPerformed(evt);
            }
        });
        jMenu1.add(menuChambre);

        menuClient.setText("Client");
        menuClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientActionPerformed(evt);
            }
        });
        jMenu1.add(menuClient);

        menuReservation.setText("Reservation");
        menuReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReservationActionPerformed(evt);
            }
        });
        jMenu1.add(menuReservation);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Recherche");

        jMenuItem1.setText("Reservation");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        menuClientReservations.setText("Réservations d’un client");
        menuClientReservations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientReservationsActionPerformed(evt);
            }
        });
        jMenu2.add(menuClientReservations);

        jMenuBar1.add(jMenu2);

        Statistiques.setText("Statistiques");

        menuOccupation.setText("Taux d’occupation");
        menuOccupation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOccupationActionPerformed(evt);
            }
        });
        Statistiques.add(menuOccupation);

        jMenuBar1.add(Statistiques);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(desktop))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(desktop))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuChambreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuChambreActionPerformed
        // TODO add your handling code here:
        ChambreForm cf = new ChambreForm();  
        desktop.add(cf);   
        cf.setVisible(true);
        cf.setLocation(
        (desktop.getWidth() - cf.getWidth()) / 2,
        (desktop.getHeight() - cf.getHeight()) / 2
    );

    }//GEN-LAST:event_menuChambreActionPerformed

    private void menuClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientActionPerformed
        // TODO add your handling code here:
        ClientForm cf = new ClientForm();
        desktop.add(cf);
        cf.setVisible(true);

        cf.setLocation(
            (desktop.getWidth() - cf.getWidth()) / 2,
            (desktop.getHeight() - cf.getHeight()) / 2
        );
    }//GEN-LAST:event_menuClientActionPerformed

    private void menuReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReservationActionPerformed
        // TODO add your handling code here:
         ReservationForm rf = new ReservationForm();
        desktop.add(rf);
        rf.setVisible(true);

        rf.setLocation(
            (desktop.getWidth() - rf.getWidth()) / 2,
            (desktop.getHeight() - rf.getHeight()) / 2
        );
    }//GEN-LAST:event_menuReservationActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        RechercheReservationForm rf = new RechercheReservationForm();  
    desktop.add(rf);
    rf.setVisible(true);

    // Center it inside the desktop pane
    rf.setLocation(
        (desktop.getWidth() - rf.getWidth()) / 2,
        (desktop.getHeight() - rf.getHeight()) / 2
    );
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuClientReservationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientReservationsActionPerformed
        // TODO add your handling code here:
        RechercheClientReservationForm f = new RechercheClientReservationForm();
        desktop.add(f);
        f.setVisible(true);

        f.setLocation(
            (desktop.getWidth() - f.getWidth()) / 2,
            (desktop.getHeight() - f.getHeight()) / 2
        );
    }//GEN-LAST:event_menuClientReservationsActionPerformed

    private void menuOccupationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOccupationActionPerformed
        // TODO add your handling code here:
        OccupationStatsForm os = new OccupationStatsForm();
        desktop.add(os);
        os.setVisible(true);
        os.setLocation(
        (desktop.getWidth() - os.getWidth()) / 2,
        (desktop.getHeight() - os.getHeight()) / 2
    );
    }//GEN-LAST:event_menuOccupationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Main m = new Main();
                m.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH); // full screen
                m.setLocationRelativeTo(null); // center on screen
                m.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Statistiques;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem menuChambre;
    private javax.swing.JMenuItem menuClient;
    private javax.swing.JMenuItem menuClientReservations;
    private javax.swing.JMenuItem menuOccupation;
    private javax.swing.JMenuItem menuReservation;
    // End of variables declaration//GEN-END:variables
}
