/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import entities.Chambre;
import entities.Reservation;
import java.time.LocalDate;
import java.time.ZoneId;
import javax.swing.ButtonGroup;
import javax.swing.table.DefaultTableModel;
import services.ReservationService;

/**
 *
 * @author USER
 */
public class RechercheReservationForm extends javax.swing.JInternalFrame {

    ReservationService rs = new ReservationService();


    /**
     * Creates new form RecherchReservation
     */
    public RechercheReservationForm() {
        initComponents();
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        ButtonGroup groupType = new ButtonGroup();
        groupType.add(radioSingle);
        groupType.add(radioDouble);
        groupType.add(radioSuite);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        DateD1 = new com.toedter.calendar.JDateChooser();
        DateF1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BnReservation = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableReservationSearch = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        BnChambre = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableChambresDisponibles = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        DateD2 = new com.toedter.calendar.JDateChooser();
        DateF2 = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        radioSingle = new javax.swing.JRadioButton();
        radioDouble = new javax.swing.JRadioButton();
        radioSuite = new javax.swing.JRadioButton();
        BnFiltrer = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableChambresParType = new javax.swing.JTable();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Recherche de réservations entre deux dates"));

        jLabel1.setText("Date début :");

        jLabel2.setText("Date fin :");

        BnReservation.setText("Réservations entre dates");
        BnReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnReservationActionPerformed(evt);
            }
        });

        tableReservationSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID ", "Chambre ", "Client ", "Début ", "Fin"
            }
        ));
        jScrollPane2.setViewportView(tableReservationSearch);
        if (tableReservationSearch.getColumnModel().getColumnCount() > 0) {
            tableReservationSearch.getColumnModel().getColumn(3).setHeaderValue("Début ");
            tableReservationSearch.getColumnModel().getColumn(4).setHeaderValue("Fin");
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BnReservation)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(DateD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(DateF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(203, 203, 203))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DateF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BnReservation)
                .addGap(13, 13, 13)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Chambres disponibles entre deux dates"));

        BnChambre.setText("Chambres disponibles");
        BnChambre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnChambreActionPerformed(evt);
            }
        });

        tableChambresDisponibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numéro", "Type", "Prix par nuit"
            }
        ));
        jScrollPane1.setViewportView(tableChambresDisponibles);

        jLabel3.setText("Date début :");

        jLabel4.setText("Date fin :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel3)
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BnChambre)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(DateD2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)
                                .addComponent(jLabel4)
                                .addGap(55, 55, 55)
                                .addComponent(DateF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DateF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateD2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BnChambre)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtrage des chambres par type "));

        jLabel5.setText("Type de chambre :");

        radioSingle.setText("Single");

        radioDouble.setText("Double");

        radioSuite.setText("Suite");

        BnFiltrer.setText("Filtrer");
        BnFiltrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnFiltrerActionPerformed(evt);
            }
        });

        tableChambresParType.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Prix pa nuit"
            }
        ));
        jScrollPane3.setViewportView(tableChambresParType);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addGap(46, 46, 46)
                .addComponent(radioSingle)
                .addGap(96, 96, 96)
                .addComponent(radioDouble)
                .addGap(121, 121, 121)
                .addComponent(radioSuite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BnFiltrer)
                .addGap(46, 46, 46))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(radioSingle)
                    .addComponent(radioDouble)
                    .addComponent(radioSuite)
                    .addComponent(BnFiltrer))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BnReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnReservationActionPerformed
        // TODO add your handling code here:
        try {
        // Get dates
       LocalDate d1 = DateD1.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
    LocalDate d2 = DateF1.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();


        // Prepare table
        DefaultTableModel model = (DefaultTableModel) tableReservationSearch.getModel();
        model.setRowCount(0);

        // Search all reservations
        for (Reservation r : rs.findAll()) {
            if (!r.getDateDebut().isAfter(d2) && !r.getDateFin().isBefore(d1)) {
                model.addRow(new Object[]{
                        r.getId(),
                        r.getChambre().getNumero(),
                        r.getClient().getNom(),
                        r.getDateDebut(),
                        r.getDateFin()
                });
            }
        }

        } catch (Exception e) {
            System.out.println("Erreur : " + e.getMessage());
        }
    }//GEN-LAST:event_BnReservationActionPerformed

    private void BnChambreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnChambreActionPerformed
        // TODO add your handling code here:
        try {
        // Get dates
        LocalDate d1 = DateD2.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate d2 = DateF2.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

        // Prepare table
        DefaultTableModel model = (DefaultTableModel) tableChambresDisponibles.getModel();
        model.setRowCount(0);

        // Get available rooms from ReservationService
        for (Chambre ch : rs.findChambresDisponibles(d1, d2)) {
            model.addRow(new Object[]{
                    ch.getNumero(),
                    ch.getType(),
                    ch.getPrixParNuit()
            });
        }

        } catch (Exception e) {
            System.out.println("Erreur : " + e.getMessage());
        }
        
    }//GEN-LAST:event_BnChambreActionPerformed

    private void BnFiltrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnFiltrerActionPerformed
        // TODO add your handling code here:
        try {
        // Type of room
        String type = "";

        if (radioSingle.isSelected()) type = "Single";
        else if (radioDouble.isSelected()) type = "Double";
        else if (radioSuite.isSelected()) type = "Suite";
        else {
            System.out.println("Sélectionnez un type !");
            return;
        }

        // Prepare the table
        DefaultTableModel model = (DefaultTableModel) tableChambresParType.getModel();
        model.setRowCount(0);

        // Load rooms of this type (no date filter)
        for (Chambre c : rs.findChambresDisponiblesParType(type, LocalDate.MIN, LocalDate.MAX)) {
            model.addRow(new Object[]{
                c.getNumero(),
                c.getPrixParNuit()
            });
        }

        } catch (Exception e) {
            System.out.println("Erreur : " + e.getMessage());
        }
    }//GEN-LAST:event_BnFiltrerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BnChambre;
    private javax.swing.JButton BnFiltrer;
    private javax.swing.JButton BnReservation;
    private com.toedter.calendar.JDateChooser DateD1;
    private com.toedter.calendar.JDateChooser DateD2;
    private com.toedter.calendar.JDateChooser DateF1;
    private com.toedter.calendar.JDateChooser DateF2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton radioDouble;
    private javax.swing.JRadioButton radioSingle;
    private javax.swing.JRadioButton radioSuite;
    private javax.swing.JTable tableChambresDisponibles;
    private javax.swing.JTable tableChambresParType;
    private javax.swing.JTable tableReservationSearch;
    // End of variables declaration//GEN-END:variables
}
