/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import entities.Chambre;
import entities.Client;
import entities.Reservation;
import java.time.LocalDate;
import java.time.ZoneId;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import services.ChambreService;
import services.ClientService;
import services.ReservationService;

/**
 *
 * @author USER
 */
public class ReservationForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form ReservationForm
     */
    ReservationService rs = new ReservationService();
    ChambreService cs = new ChambreService();
    ClientService cls = new ClientService();

    int selectedId = -1;

    public ReservationForm() {
        initComponents();
        loadChambres();
        loadClients();
        loadData();
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);


    }

    private void clearFields() {
        comboNumero.setSelectedIndex(-1);   // deselect chambre
        comboClient.setSelectedIndex(-1);   // deselect client
        txtDebut.setDate(null);
        txtFin.setDate(null);
    }


    private void loadData() {
        DefaultTableModel model = (DefaultTableModel) TableReservation.getModel();
        model.setRowCount(0);

        for (Reservation r : rs.findAll()) {
            model.addRow(new Object[]{
                r.getId(),
                r.getChambre().getNumero(),
                r.getClient().getNom(),
                r.getDateDebut(),
                r.getDateFin()
            });
        }
    }

    private void loadChambres() {
        comboNumero.removeAllItems();
        for (Chambre c : cs.findAll()) {
            comboNumero.addItem(String.valueOf(c.getNumero()));
        }
    }

    private void loadClients() {
        comboClient.removeAllItems();
        for (Client c : cls.findAll()) {
            comboClient.addItem(c.getId() + " - " + c.getNom());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        bnAjouter = new javax.swing.JButton();
        bnSupprimer = new javax.swing.JButton();
        bnModifier = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableReservation = new javax.swing.JTable();
        panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDebut = new com.toedter.calendar.JDateChooser();
        txtFin = new com.toedter.calendar.JDateChooser();
        comboNumero = new javax.swing.JComboBox();
        comboClient = new javax.swing.JComboBox();

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Action"));

        bnAjouter.setText("Ajouter");
        bnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnAjouterActionPerformed(evt);
            }
        });

        bnSupprimer.setText("Supprimer");
        bnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnSupprimerActionPerformed(evt);
            }
        });

        bnModifier.setText("modifier");
        bnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnModifierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bnSupprimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bnAjouter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bnModifier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(bnAjouter)
                .addGap(18, 18, 18)
                .addComponent(bnSupprimer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bnModifier)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Lists des reservations"));

        TableReservation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Chambre", "Client", "Date de debut", "Date de fin"
            }
        ));
        TableReservation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableReservationMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableReservation);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 807, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(177, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(178, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Information des reservation "));
        panel.setToolTipText("");
        panel.setName(""); // NOI18N

        jLabel1.setText("Numero de chambre :");

        jLabel2.setText("Date de debut :");

        jLabel3.setText("Client Id :");

        jLabel4.setText("Date Fin  :");

        comboNumero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboClient.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboClientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(44, 44, 44)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtDebut, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                        .addComponent(txtFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(comboNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboClient, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtDebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnAjouterActionPerformed
        // TODO add your handling code here:
        try {
        int numChambre = Integer.parseInt(comboNumero.getSelectedItem().toString());
        int idClient = Integer.parseInt(comboClient.getSelectedItem().toString().split(" - ")[0]);

        Chambre ch = cs.findById(numChambre);
        Client cl = cls.findById(idClient);

        if (ch == null || cl == null) {
            JOptionPane.showMessageDialog(this, "Chambre ou Client introuvable !");
            return;
        }

        LocalDate d1 = txtDebut.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate d2 = txtFin.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

        // Confirmation popup before adding
        int confirmation = JOptionPane.showConfirmDialog(
            this, 
            "Voulez-vous vraiment ajouter la réservation?\n" +
            "Chambre: " + numChambre + "\n" +
            "Client: " + cl.getNom() + "\n" +
            "Du: " + d1 + " au: " + d2, 
            "Confirmation d'ajout de réservation", 
            JOptionPane.YES_NO_OPTION
        );
        
        if (confirmation == JOptionPane.YES_OPTION) {
            Reservation r = new Reservation(0, ch, cl, d1, d2);

            if (rs.create(r)) {
                JOptionPane.showMessageDialog(this, "Réservation ajoutée avec succès!");
                clearFields();
                loadData();
            } else {
                JOptionPane.showMessageDialog(this, "Erreur : chambre non disponible pour ces dates!");
            }
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur : " + e.getMessage());
        }
    }//GEN-LAST:event_bnAjouterActionPerformed

    private void bnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnSupprimerActionPerformed
        // TODO add your handling code here:
        try {
        if (selectedId == -1) {
            JOptionPane.showMessageDialog(this, "Aucune réservation sélectionnée !");
            return;
        }

        Reservation r = rs.findById(selectedId);

        if (r == null) {
            JOptionPane.showMessageDialog(this, "Réservation introuvable !");
            return;
        }

        // Confirmation popup before deletion
        int confirmation = JOptionPane.showConfirmDialog(
            this, 
            "Voulez-vous vraiment supprimer la réservation #" + selectedId + "?\n" +
            "Chambre: " + r.getChambre().getNumero() + "\n" +
            "Client: " + r.getClient().getNom(), 
            "Confirmation de suppression", 
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );
        
        if (confirmation == JOptionPane.YES_OPTION) {
            if (rs.delete(r)) {
                JOptionPane.showMessageDialog(this, "Réservation supprimée avec succès!");
                clearFields();
                loadData();
                selectedId = -1; // Reset selected ID
            } else {
                JOptionPane.showMessageDialog(this, "Erreur lors de la suppression!");
            }
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur : " + e.getMessage());
        }
    }//GEN-LAST:event_bnSupprimerActionPerformed

    private void bnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnModifierActionPerformed
        // TODO add your handling code here:
        try {
        if (selectedId == -1) {
            JOptionPane.showMessageDialog(this, "Aucune réservation sélectionnée !");
            return;
        }

        int numChambre = Integer.parseInt(comboNumero.getSelectedItem().toString());
        int idClient = Integer.parseInt(comboClient.getSelectedItem().toString().split(" - ")[0]);

        Chambre ch = cs.findById(numChambre);
        Client cl = cls.findById(idClient);

        if (ch == null || cl == null) {
            JOptionPane.showMessageDialog(this, "Chambre ou Client introuvable !");
            return;
        }

        LocalDate d1 = txtDebut.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate d2 = txtFin.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

        // Confirmation popup before modification
        int confirmation = JOptionPane.showConfirmDialog(
            this, 
            "Voulez-vous vraiment modifier la réservation #" + selectedId + "?\n" +
            "Nouvelle chambre: " + numChambre + "\n" +
            "Nouveau client: " + cl.getNom() + "\n" +
            "Nouvelles dates: Du " + d1 + " au " + d2, 
            "Confirmation de modification", 
            JOptionPane.YES_NO_OPTION
        );
        
        if (confirmation == JOptionPane.YES_OPTION) {
            Reservation r = new Reservation(selectedId, ch, cl, d1, d2);

            if (rs.update(r)) {
                JOptionPane.showMessageDialog(this, "Réservation modifiée avec succès!");
                clearFields();
                loadData();
                selectedId = -1; // Reset selected ID
            } else {
                JOptionPane.showMessageDialog(this, "Erreur : chambre non disponible pour ces dates!");
            }
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur : " + e.getMessage());
        }

    }//GEN-LAST:event_bnModifierActionPerformed

    private void TableReservationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableReservationMouseClicked
        // TODO add your handling code here:
        int row = TableReservation.getSelectedRow();

        selectedId = Integer.parseInt(TableReservation.getValueAt(row, 0).toString());

        // Chambre number from column 1
        String chambreNum = TableReservation.getValueAt(row, 1).toString();
        comboNumero.setSelectedItem(chambreNum);

        // Client NOM from column 2 → find matching "id - nom"
        String clientName = TableReservation.getValueAt(row, 2).toString();

        for (int i = 0; i < comboClient.getItemCount(); i++) {
            String item = comboClient.getItemAt(i).toString();
            if (item.endsWith(" - " + clientName) || item.contains(" " + clientName)) {
                comboClient.setSelectedIndex(i);
                break;
            }
        }

        // Dates
        txtDebut.setDate(java.sql.Date.valueOf(TableReservation.getValueAt(row, 3).toString()));
        txtFin.setDate(java.sql.Date.valueOf(TableReservation.getValueAt(row, 4).toString()));
    }//GEN-LAST:event_TableReservationMouseClicked

    private void comboClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboClientActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableReservation;
    private javax.swing.JButton bnAjouter;
    private javax.swing.JButton bnAjouter1;
    private javax.swing.JButton bnAjouter2;
    private javax.swing.JButton bnAjouter3;
    private javax.swing.JButton bnModifier;
    private javax.swing.JButton bnModifier1;
    private javax.swing.JButton bnModifier2;
    private javax.swing.JButton bnModifier3;
    private javax.swing.JButton bnSupprimer;
    private javax.swing.JButton bnSupprimer1;
    private javax.swing.JButton bnSupprimer2;
    private javax.swing.JButton bnSupprimer3;
    private javax.swing.JComboBox comboClient;
    private javax.swing.JComboBox comboNumero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel;
    private com.toedter.calendar.JDateChooser txtDebut;
    private com.toedter.calendar.JDateChooser txtFin;
    // End of variables declaration//GEN-END:variables
}
